### ISSUE TITLE
create ReadStream for audio file

### ISSUE THREAD

**Issue by Harshil-Jani** [osenorth/AR-Personal-Assistant#5]
https://github.com/osenorth/AR-Personal-Assistant/pull/3/files#diff-9267142ac484742251eaf6741dc67d6c9d5292eadddc9304606b010ff234f41dR36

Here, API needs a ReadStream for the audio file. But, Currently, I have hardcoded the file from my machine. It needs to be made generic for the uploaded file from frontend. I have tried with multer but it has lots of NextJS compatibility issues. Need to see how this can be achieved.

**Comment by Harshil-Jani** [comment]
Closing since we are currently no longer using whisper anymore. In case if need arises we can always reopen this.

**Comment by bingJunior** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [3](https://trello.com/c/w92KdcF6/3-3)
